version: '3'
services:

  database:
    container_name: postgresql-db_1
    image: postgres:16.1
    environment:
      POSTGRES_DB: teaching_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    networks:
      - teaching-network

  mqtt_broker:
    image: 127.0.0.1:5000/hivemq
    build: ./hive-mq
    container_name: hivemq
    ports:
      - 1883:1883
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - teaching-network
      
  angular-website:
    depends_on:
      - java_organizer
      - java_grading
    build: ./angular-website
    container_name: angular-website-app
    ports:
      - 4200:4200
    links:
      - java_organizer
      - java_grading
    networks:
      - teaching-network
      
  java_organizer:
    depends_on:
      - database
      - mqtt_broker
    build: ./java_organizer
    restart: on-failure
    container_name: java_organizer-app
    environment:
      HIVEMQ_URI: mqtt_broker
    ports:
      - 8081:8081
    links:
      - database
      - mqtt_broker
    networks:
      - teaching-network
      
  java_grading:
    depends_on:
      - database
      - mqtt_broker
      - java_organizer
    build: ./java_grading
    restart: on-failure
    container_name: java_grading-app
    environment:
      POSTGRESQL_URI: jdbc:postgresql://database:5432/teaching_database
      HIVEMQ_URI: mqtt_broker
    ports:
      - 8082:8082
    links:
      - database
      - mqtt_broker
      - java_organizer
    networks:
      - teaching-network
      
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - java_grading
    networks:
      - teaching-network

networks:
  teaching-network:
    driver: bridge
